# Generated by Django 3.1.7 on 2021-04-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myTrains',
            fields=[
                ('arrival', models.TimeField(auto_now=True)),
                ('day', models.CharField(max_length=50)),
                ('train_name', models.CharField(max_length=300)),
                ('station_name', models.CharField(max_length=300)),
                ('station_code', models.CharField(max_length=300)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_number', models.IntegerField()),
                ('departure', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train_Btw_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_No', models.IntegerField()),
                ('Train_Name', models.CharField(max_length=300)),
                ('Source_Station_Name', models.CharField(max_length=300)),
                ('Destination_Station_Name', models.CharField(max_length=300)),
                ('days', models.CharField(max_length=50)),
            ],
        ),
    ]
