# Generated by Django 3.1.7 on 2021-05-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='capital',
            field=models.CharField(default='', max_length=100),
        ),
    ]
