# Generated by Django 3.1.7 on 2021-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210615_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='capital',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='history',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='imag2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='imag3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='imag4',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='imag5',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='imag6',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='imag7',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='imag8',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='img1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
