# Generated by Django 3.1.7 on 2021-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210615_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrains',
            name='AC1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mytrains',
            name='AC2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mytrains',
            name='AC3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mytrains',
            name='general',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mytrains',
            name='sleeper',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mytrains',
            name='train_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
