# Generated by Django 3.1.7 on 2021-06-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210615_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrains',
            name='station_code',
        ),
    ]
