# Generated by Django 3.1.7 on 2021-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_mytrains_station_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrains',
            name='AC1',
        ),
        migrations.RemoveField(
            model_name='mytrains',
            name='AC2',
        ),
        migrations.RemoveField(
            model_name='mytrains',
            name='AC3',
        ),
        migrations.RemoveField(
            model_name='mytrains',
            name='general',
        ),
        migrations.RemoveField(
            model_name='mytrains',
            name='sleeper',
        ),
        migrations.AddField(
            model_name='train_btw_station',
            name='AC1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='train_btw_station',
            name='AC2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='train_btw_station',
            name='AC3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='train_btw_station',
            name='general',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='train_btw_station',
            name='sleeper',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mytrains',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
