# Generated by Django 3.1.7 on 2021-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210615_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrains',
            name='station_name',
        ),
        migrations.AddField(
            model_name='mytrains',
            name='Destination_Station_Name',
            field=models.CharField(default=8.99644640367055e-05, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytrains',
            name='Source_Station_Name',
            field=models.CharField(default=8.99644640367055e-05, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mytrains',
            name='arrival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mytrains',
            name='departure',
            field=models.TimeField(),
        ),
    ]
