# Generated by Django 3.1.7 on 2021-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20210615_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_name', models.CharField(default='', max_length=100)),
                ('Bus_No', models.IntegerField()),
                ('Source_Station_Name', models.CharField(max_length=300)),
                ('Destination_Station_Name', models.CharField(max_length=300)),
                ('days', models.CharField(max_length=50)),
                ('sleeper', models.IntegerField(blank=True, default=0, null=True)),
                ('AC', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
