# Generated by Django 3.1.7 on 2021-06-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_my_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myTrains',
        ),
    ]
