# Generated by Django 3.1.7 on 2021-06-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_delete_mytrains'),
    ]

    operations = [
        migrations.CreateModel(
            name='myTrains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField(blank=True, default=0, null=True)),
                ('arrival', models.TimeField()),
                ('day', models.CharField(max_length=50)),
                ('train_name', models.CharField(max_length=300)),
                ('Source_Station_Name', models.CharField(max_length=300)),
                ('Destination_Station_Name', models.CharField(max_length=300)),
                ('departure', models.TimeField()),
            ],
        ),
    ]
