# Generated by Django 3.1.7 on 2021-06-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_my_flight_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='cheap_hotel',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='five_star_hotel',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='mid_range_hotel',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
