# Generated by Django 3.1.7 on 2021-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20210620_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_btw_station',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
