# Generated by Django 3.1.7 on 2021-06-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_train_btw_station_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_btw_station',
            old_name='date',
            new_name='date1',
        ),
        migrations.AddField(
            model_name='train_btw_station',
            name='date2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
