# Generated by Django 3.1.7 on 2021-06-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20210622_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_btw_station',
            name='date1',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='train_btw_station',
            name='date2',
            field=models.DateTimeField(),
        ),
    ]
