# Generated by Django 3.1.7 on 2021-06-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20210622_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_btw_station',
            old_name='date2',
            new_name='qry_date',
        ),
    ]
