# Generated by Django 3.1.7 on 2021-06-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20210626_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Destination_Station_Name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='Source_Station_Name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='Train_Name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='Train_No',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
