# Generated by Django 3.1.7 on 2021-06-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_booking_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
    ]
