# Generated by Django 3.1.7 on 2021-06-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20210627_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='days',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_date',
        ),
    ]
