# Generated by Django 3.1.7 on 2021-06-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20210627_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='age',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.CharField(max_length=300),
        ),
    ]
