# Generated by Django 3.1.7 on 2021-06-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20210627_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
