# Generated by Django 3.1.7 on 2021-06-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_busbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_No', models.IntegerField()),
                ('Flight_Name', models.CharField(max_length=300)),
                ('Source_Station_Name', models.CharField(max_length=300)),
                ('Destination_Station_Name', models.CharField(max_length=300)),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('contact_number', models.CharField(max_length=300)),
                ('contact_gender', models.CharField(default='male', max_length=10)),
                ('price', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
    ]
